name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for tagging'
        required: true
        type: string
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required to fetch entire git history

    - name: Configure Git
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
    - name: Create and push version tag
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version }}
      run: |
        git fetch --tags
        git tag ${{ github.event.inputs.version }}
        git push origin ${{ github.event.inputs.version }}
              

    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: JUnit Report Action
      # You may pin to the exact commit or the version.
      # uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3
      uses: mikepenz/action-junit-report@v5.6.2
      with:
        report_paths: "**/reports/**/*.xml"
        fail_on_failure: false
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
